version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - revive
    - gosec
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    paths:
      - vendor
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
run:
  timeout: 5m
