version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - misspell
    - revive
    - gosec
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    paths:
      - vendor
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
run:
  timeout: 5m
